go.mod, tools/go.mod
Bump Go version from 1.23.4 to 1.23.5. 
Includes security changes to the standard library, fixing some linter errors.
=> deps(go.mod): bump Go version to 1.23.5 in go.mod and tools/go.mod

go.mod, tools/go.mod
Bump Go version from 1.23.5 to 1.23.6.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.6+label%3ACherryPickApproved
=> deps(go.mod): bump Go version to 1.23.6 in go.mod and tools/go.mod

.golangci.yaml
The new version of `golangci-lint` seems to be more strict on where settings are. This moves `nolintlint` from the top level into `linters-settings`.
=> fix(.golangci.yaml): Fix nolintlint in golangci-lint config 

cmd/insights/commands/collect.go
Fix CLI collect command report pretty printing, such that instead of printing bytes, it prints the actual JSON.
---
UDENG-6222
=> fix(collect): Fix CLI collect command report printing

cmd/insights/integration-tests/testdata/TestCollect/golden/platform_darwin, cmd/insights/integration-tests/testdata/TestCollect/golden/platform_linux, cmd/insights/integration-tests/testdata/TestCollect/golden/platform_windows, cmd/insights/integration-tests/testdata/TestCollect/golden/true_bad-ext, cmd/insights/integration-tests/testdata/TestCollect/golden/true_normal, cmd/insights/integration-tests/testdata/TestCollect/golden/true_normal_force, cmd/insights/integration-tests/testdata/TestCollect/golden/true_normal_force_period, cmd/insights/integration-tests/testdata/TestCollect/golden/true_normal_global_bad-file, cmd/insights/integration-tests/testdata/TestCollect/golden/true_normal_global_false, cmd/insights/integration-tests/testdata/TestCollect/golden/true_normal_maxreports, cmd/insights/integration-tests/testdata/TestCollect/golden/unknown-a_normal, internal/collector/collector.go, internal/collector/sysinfo/hardware/hardware.go, internal/collector/sysinfo/software/software.go, internal/collector/sysinfo/testdata/TestCollect/golden/hardware_and_software_error_warns, internal/collector/testdata/TestCompile/golden/basic, internal/collector/testdata/TestCompile/golden/dry_run, internal/collector/testdata/TestCompile/golden/duplicate_report_force, internal/collector/testdata/TestCompile/golden/with_sourcemetrics, internal/collector/testdata/TestWrite/golden/basic, internal/collector/testdata/TestWrite/golden/max_reports, internal/collector/testdata/TestWrite/golden/no_dir
For clarity, use the omitzero and omitempty tags for relevant parts of the structs being compiled into the JSON report. 
This is primarily done for sections, and it is not applied to all fields for cases where it is expected that one part of the section was gotten, but was not for whatever reason. For example, if for BIOS, vendor was filled but not version, both fields will remain.
---
UDENG-6329
=> feat(collector): omitzero-omitempty non critical parts of the JSON report

cmd/insights/integrationtests.go
Fix error formatting in integration tests for syninfo handling that broke cmd main tests.
Small spelling fix to American English.
=> fix(integrationtests): Fix error formatting in integration tests sysinfo handling; spelling fix

go.mod, tools/go.mod
Bumps Go version to 1.24.1 in go.mod and tools/go.mod from 1.24.0.
=> deps(go.mod): Bump Go version to 1.24.1 in go.mod and tools/go.mod

internal/collector/sysinfo/hardware/hardware.go, internal/collector/sysinfo/hardware/hardware_darwin.go, internal/collector/sysinfo/hardware/hardware_linux.go, internal/collector/sysinfo/hardware/hardware_linux_test.go, internal/collector/sysinfo/hardware/hardware_windows.go, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/wsl_1_hardware_information
Add special handling for the WSL 1 case for collectDisk, where if lsblk fails, the error is silenced as this is expected.
---
[UDENG-6395](https://warthogs.atlassian.net/browse/UDENG-6395)
[UDENG-6395]: https://warthogs.atlassian.net/browse/UDENG-6395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(sysinfo/hardware): Add special handling for the WSL 1 case for collectDisk

cmd/insights/commands/collect.go, cmd/insights/commands/consent.go, cmd/insights/commands/root.go, cmd/insights/commands/upload.go
Improve command usage descriptions for clarity and consistency.
Hide `insights-dir` flag for the consent command.
---
UDENG-6487
=> feat(cmd): Improve command usage descriptions for clarity and consistency

ubuntu-insights-initial-setup
Fix the consent command in the setup script to use 'linux' instead of 'ubuntu' to match the expected source for runtime.GOOS
=> fix(ubuntu-insights-initial-setup): Fix setup consent to use 'linux' instead of 'ubuntu'

internal/collector/sysinfo/platform/platform_linux.go, internal/collector/sysinfo/platform/platform_linux_test.go, internal/collector/sysinfo/platform/testdata/TestCollectLinux/golden/other_virt_type_(uml)_with_pro_attached
Patch to prevent a warning from being logged when `systemd-detect-virt` returns `none`, even though it returns with exit code 1.
---
UDENG-6493
=> fix(platform): Don't log warning when systemd-detect-virt returns 'none'

internal/collector/sysinfo/hardware/hardware_windows.go, internal/collector/sysinfo/hardware/hardware_windows_test.go, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/bad_memory_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/error_cpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/error_gpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/error_memory_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/error_partition_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/error_product_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/error_screen_resolution_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/error_screen_size_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/garbage_memory_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/malicious_disk_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/malicious_partition_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/missing_cpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/missing_gpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/missing_memory_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/missing_partition_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/missing_product_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/missing_screen_resolution_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/missing_screen_size_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/negative_memory_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/negative_valued_cpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/regular_hardware_information, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/zero_valued_cpu_information
Fix windows disk partition collection to remove the assumption that disks are printed in order of their indices. 
Added additional tests.
---
UDENG-6500
=> fix(hardware): Fix windows disk-partition collection

internal/collector/sysinfo/hardware/hardware_linux.go, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/bad_block_nesting_depth, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/cpu_information_with_negative_values_is_handled, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/error_block_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/error_cpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/garbage_block_information_is_empty, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/garbage_cpu_information_is_empty, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/missing_block_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/missing_cpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/missing_gpu_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/missing_gpus, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/missing_memory_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/missing_product_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/regular_hardware_information, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/some_cpu_information_is_derived_when_missing, internal/collector/sysinfo/hardware/testdata/TestCollectLinux/golden/wsl_hardware_information_with_xrandr
On Linux, to get screen information, xrandr is currently being used. While this seems acceptable for most cases, including when the backend is Wayland, it does not provide the correct physical resolution, and only provides post-scaling resolution. Thus, for now, the report should not include possibly false physical resolution.
---
[UDENG-6569](https://warthogs.atlassian.net/browse/UDENG-6569)
[UDENG-6569]: https://warthogs.atlassian.net/browse/UDENG-6569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(hardware_linux): Remove physical resolution field from Linux reports

internal/collector/sysinfo/hardware/hardware_windows.go, internal/collector/sysinfo/hardware/hardware_windows_test.go, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/single_disk_and_part
Fixes a collection failure on Windows that occurred when there was only a single disk, or a single partition. Also adds a new test to cover this case.
---
[UDENG-6605](https://warthogs.atlassian.net/browse/UDENG-6605)
[UDENG-6605]: https://warthogs.atlassian.net/browse/UDENG-6605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(hardware): Fix Windows single disk and single partition collection

autostart/systemd/ubuntu-insights-collect.service, autostart/systemd/ubuntu-insights-collect.timer, autostart/systemd/ubuntu-insights-upload.service, autostart/systemd/ubuntu-insights-upload.timer
A few modifications for the systemd units.
- `ubuntu-insights-collect.service`: Type=simple. Make this oneshot
- `ubuntu-insights-collect.timer`: `Unit=ubuntu-insights-collect.service` -> drop the .service
- `ubuntu-insights-upload.service`: Type: Make this oneshot
- `ubuntu-insights-upload.timer`: Adjust the timer to trigger slightly after collection; drop the .service
---
[UDENG-6602](https://warthogs.atlassian.net/browse/UDENG-6602)
[UDENG-6602]: https://warthogs.atlassian.net/browse/UDENG-6602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(systemd): Modifications for systemd units

internal/collector/sysinfo/hardware/hardware_windows.go, internal/collector/sysinfo/hardware/hardware_windows_test.go, internal/collector/sysinfo/hardware/testdata/TestCollectWindows/golden/ignores_virtual_disks
Ignore Windows virtual disks, and do not add them to the report.
Also fixed some minor spelling mistakes in hardware_windows
---
[UDENG-6532](https://warthogs.atlassian.net/browse/UDENG-6532)
[UDENG-6532]: https://warthogs.atlassian.net/browse/UDENG-6532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(hardware): Ignore Windows virtual disks

.github/workflows/systemd-verify.yaml, autostart/systemd/ubuntu-insights-collect.service, autostart/systemd/ubuntu-insights-upload.service
Fix systemd containment permissions that relate to Wayland screen info collection. 
The current settings are too restrictive and break display collection via Wayland if `ubuntu-insights` is triggered using systemd. This is due to `RestrictAddressFamilies=NONE` which should be set as `AF_UNIX`.
There also resolves an additional issue where certain settings don’t function properly, and are being ignored, resulting in warnings. While functionality is not affected, this could have issues in the future should those settings work, and there is an unexpected adverse effect on the functionality of `ubuntu-insights`.
---
[UDENG-6821](https://warthogs.atlassian.net/browse/UDENG-6821)
[UDENG-6821]: https://warthogs.atlassian.net/browse/UDENG-6821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> fix(systemd): Fix systemd containment permissions related to Wayland collection

internal/uploader/uploader_test.go
Add mutex to synchronize access in TestBackoffUpload's httptest server. This should fix a rare race condition that often results in `go test --race` failure, especially on macOS.
---
[UDENG-6876](https://warthogs.atlassian.net/browse/UDENG-6876)
[UDENG-6876]: https://warthogs.atlassian.net/browse/UDENG-6876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(uploader): Fix flaky TestBackoffUpload test race condition

debian/changelog
Update the Debian changelog to target Questing instead of Plucky. Also bumps the version to ~ppa7 from 6.
=> build(changelog): Update the debian changelog to target questing

internal/server/ingest/ingest.go, internal/server/ingest/ingest_test.go
Ensures that when the ingest service quits in a none-forceful manner, that `Quit(false)` blocks until all app workers close.
This should help with some test flakiness that has been observed related to file cleanup, particularly errors similar to `TempDir RemoveAll cleanup: unlinkat /tmp/TestRunAfterQuitErrors376364591/001/fixtures: directory not empty`.
---
[UDENG-6985](https://warthogs.atlassian.net/browse/UDENG-6985)
[UDENG-6985]: https://warthogs.atlassian.net/browse/UDENG-6985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ingest): Non-force Quit ensures all app workers close

cmd/ingest-service/daemon/daemon.go, cmd/insights/commands/root.go, cmd/web-service/daemon/daemon.go
Hide the completion command from help and man. The completion command will still exist, but will just be hidden.
Closes #105 
---
[UDENG-7061](https://warthogs.atlassian.net/browse/UDENG-7061)
[UDENG-7061]: https://warthogs.atlassian.net/browse/UDENG-7061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Hide completion command from help and man

debian/control, debian/rules
Using golang build package system is not enough, we need to ensure that golang debhelper is hooked in too to populate that field.
Fix a missing trailing comma too.
=> fix: Ensure Built-Using is populated

README.md
Update the README examples.
- Include `collectionTime`
- Bump versions
- Fix field names for Ubuntu Desktop `screens`
---
[UDENG-7039](https://warthogs.atlassian.net/browse/UDENG-7039)
[UDENG-7039]: https://warthogs.atlassian.net/browse/UDENG-7039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Update README examples

debian/changelog, debian/copyright, debian/install, debian/lrc.config
Update the `debian/copyright` file, include Apache 2.0 notices in deb package docs.
---
[UDENG-7001](https://warthogs.atlassian.net/browse/UDENG-7001)
[UDENG-7001]: https://warthogs.atlassian.net/browse/UDENG-7001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(debian): Update copyright and fix notice handling

debian/README.source
Add README.source file to meet the requirements needed for MIR. https://canonical-ubuntu-project.readthedocs-hosted.com/MIR/mir-reporters-template/#mir-reporters-template
Some of this might end up not being needed, but it is a little easier to include it now instead of down the road.
---
[UDENG-7110](https://warthogs.atlassian.net/browse/UDENG-7110)
[UDENG-7110]: https://warthogs.atlassian.net/browse/UDENG-7110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(debian/README.source): Add README.source

go.mod, tools/go.mod
Set the go toolchain version to 1.24.4, downgrade go to 1.24.0 in go.mod.
This is to deal with the current version of go in main being 1.24.2, allowing for the deb package to be built again. Since we use features from 1.24, the minimum version is still pegged to 1.24, but the toolchain version should generally still be the most recent patch.
Note that toolchain is set to local in `debian/rules` so it will use what is available locally.
---
[UDENG-7191](https://warthogs.atlassian.net/browse/UDENG-7191)
[UDENG-7191]: https://warthogs.atlassian.net/browse/UDENG-7191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> deps(go.mod): Set go toolchain version to 1.24.4, downgrade go to 1.24.0 in go.mod

internal/server/ingest/ingest_test.go
Increase the timeout duration in `waitWorkersEqual` to 8 seconds. This will hopefully help with flaky tests on the macOS runners, which tend to be much slower than the other runners, resulting in these sorts of timing failures.
=> tests: Increase the timeout duration in waitWorkersEqual to 8 seconds

cmd/insights/commands/collect.go, cmd/insights/commands/collect_test.go, cmd/insights/commands/root.go, cmd/insights/commands/testdata/TestCollect/golden/collect_bad-file-consent_source, cmd/insights/commands/testdata/TestCollect/golden/collect_bad-file_consent_global_source, cmd/insights/commands/testdata/TestCollect/golden/collect_basic, cmd/insights/commands/testdata/TestCollect/golden/collect_dry_run,_verbose_1, cmd/insights/commands/testdata/TestCollect/golden/collect_dry_run,_verbose_2, cmd/insights/commands/testdata/TestCollect/golden/collect_false-consent_source, cmd/insights/commands/testdata/TestCollect/golden/collect_period_overflow, cmd/insights/commands/testdata/TestCollect/golden/collect_source_invalid_json, cmd/insights/commands/testdata/TestCollect/golden/collect_source_normal, cmd/insights/commands/testdata/TestCollect/golden/collect_source_normal,_dry-run, cmd/insights/commands/testdata/TestCollect/golden/collect_source_normal,_period, cmd/insights/commands/testdata/TestCollect/golden/collect_source_normal,_period,_dry-run, cmd/insights/commands/testdata/TestCollect/golden/collect_source_normal,_period,_dry-run,_force, cmd/insights/commands/testdata/TestCollect/golden/exit_0_when_no_consent_files, internal/collector/collector.go, internal/collector/collector_test.go, internal/collector/testutils/collector.go, pkg/insights/api.go
A refactor of collector creation in order for easier usage and improved testability. 
- Refactored the `New` function in the `collector` package to return an interface instead of a concrete struct for improved mocking. This improves testability, allowing of greater separation of concerns and the mocking of collector calls at the CLI and API level.
- Refactored the `New` function in the `collector` package to accept the  `collector.Config` struct. This helps deal with some of the readability issues in the collector creation process, and better emphasis which fields can be left as 'default values' without breaking things.
- Enhanced error handling in the `Sanitize` method of `collector.Config` to ensure proper validation of configuration values. Sanitize is now called by `New` itself, so …
=> refactor: collector tweaks

insights/C/insights_types.h, insights/C/libinsights.go, insights/C/libinsightstest.go, insights/C/testdata/TestCollect/golden/all_get_converted, insights/C/testdata/TestCollect/golden/config_gets_converted, insights/C/testdata/TestCollect/golden/empty_values_are_empty, insights/C/testdata/TestCollect/golden/error_returns_error_string, insights/C/testdata/TestCollect/golden/flags_get_converted, insights/C/testdata/TestCollect/golden/metricspath_gets_converted, insights/C/testdata/TestCollect/golden/null_values_are_empty, insights/C/testdata/TestCollect/golden/sourcemetricsjson_gets_converted, insights/api.go, insights/api_test.go, insights/internal/collector/collector.go, insights/internal/collector/collector_test.go, insights/internal/collector/testdata/TestCompile/golden/with_sourcemetrics_json
This PR implements the ability for both the C and Go APIs to directly pass a JSON object when calling collect, instead of forcing it to first write the JSON it wishes to pass to a file and passing the path instead.
Note that this PR makes no changes to the CLI.
There is also a small refactoring of the C API just to make it a little easier to modify and maintain.
---
[UDENG-7222](https://warthogs.atlassian.net/browse/UDENG-7222)
[UDENG-7222]: https://warthogs.atlassian.net/browse/UDENG-7222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Implement JSON source metrics for APIs

README.md, insights/README.md, server/README.md
This PR creates individual README files for the individual components following the reorganization of the project repository. It moves the `ubuntu-insights` client usage documentation into a dedicated README within the `insights` module, and adds a bare-bones README file for the server services. All links used are relative.
Note that the collection examples are still in the root README file, but the `insights` README does link to it.
The server services README will be fleshed out further in another PR once the CLI and charm stabilizes.
---
[UDENG-7255](https://warthogs.atlassian.net/browse/UDENG-7255)
[UDENG-7255]: https://warthogs.atlassian.net/browse/UDENG-7255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Create README for individual components

server/migrations/000001_initialize-invalid_reports.up.sql, server/migrations/000002_initialize-linux.down.sql, server/migrations/000002_initialize-linux.up.sql, server/migrations/000003_initialize-windows.down.sql, server/migrations/000003_initialize-windows.up.sql, server/migrations/000004_initialize-darwin.down.sql, server/migrations/000004_initialize-darwin.up.sql, server/migrations/000005_initialize-ubuntu_report.down.sql, server/migrations/000005_initialize-ubuntu_report.up.sql
This PR implements two database optimizations into the existing migration scripts:
- Remove the unnecessary `id` primary key from all tables
- There shouldn't be a scenario where we need a unique primary key. This removes a tiny amount of overhead when inserting, as well as the storage requirements for the column and index
- Combine the `entry_time` and `optout` indexes into a single multi-column index
- It is rare that we will ever need to query the entire history of the database, and we save some storage space by combining the two indexes into a single index
---
[UDENG-7283](https://warthogs.atlassian.net/browse/UDENG-7283)
[UDENG-7283]: https://warthogs.atlassian.net/browse/UDENG-7283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Database optimizations

.github/workflows/qa-debian.yaml
This PR implements a workflow to build the ubuntu insights debian package using the docker `ubuntu:devel` image, It then attempts to install the built .deb package before running some trivial tests. For instance, it verifies the installation of a man page, systemd units, and that the CLI roughly works (only ensures exit code 0 when running commands on the runner).
Besides these mostly toy tests, the workflow is useful for ensuring that the debian package builds correctly and that there are no lintian errors.
Ideally, more robust tests should be written in the future, but that is out of scope for now.
---
[UDENG-7226](https://warthogs.atlassian.net/browse/UDENG-7226)
[UDENG-7226]: https://warthogs.atlassian.net/browse/UDENG-7226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> tests: ubuntu-insights debian package tests

insights/debian/copyright
The comment already states that the packaging is using the same license. Anyway, even without it, the pattern format is already covering it. Also, for a native package, this is standard to not split the packaging from the source.
=> maint: remove copyright duplication

server/internal/common/config/config.go, server/internal/common/config/config_test.go, server/internal/common/config/export_test.go, server/internal/common/config/testdata/TestLoad/golden/empty_json_loads, server/internal/common/config/testdata/TestLoad/golden/ignores_reserved_names, server/internal/common/config/testdata/TestLoad/golden/valid_config_loads, server/internal/ingest/ingest.go, server/internal/ingest/ingest_test.go, server/internal/webservice/handlers/handlers_test.go, server/internal/webservice/handlers/json_hander.go, server/internal/webservice/handlers/legacy_upload.go, server/internal/webservice/handlers/types.go, server/internal/webservice/handlers/upload.go, server/internal/webservice/webservice.go, server/internal/webservice/webservice_test.go
This PR modifies the server services to utilize a cached `map[string]struct{}` object to do lookups on the allow list instead of a loop or `slices.Contains` (which is a for loop underneath) . This set-like object is stored within the config manager and set whenever the `allowList` is also set. Consumers access this map by passing in the string they'd like to match within the 'set' to the `Allows` lookup method.
Though the allow list will typically be relatively small, with maybe 20 or so items, at this size it is already faster to utilize a map when trying to check if a structure contains a string (on average the breakpoint is typically around 5 items, though this could be improved with sorting heuristics).
Performance here is more important for the web service since it does a lookup …
=> feat(server): Use map to search allow list where reasonable

insights/debian/changelog
This PR syncs the changelog with what is currently present in the package uploaded to downstream as `0.2.2` while also adding some attributions that were missing for `0.2.0`.
=> build(insights): Sync changelog with 0.2.2 and add missing attributions

insights/debian/changelog, insights/debian/control
This PR bumps the control standards version to 4.7.2 to silence a lintian info message, and updates the changelog to a state ready for a release to 0.3.0.
=> build: Bump control standards version to 4.7.2 and update changelog

insights/debian/changelog, insights/debian/rules
This PR addresses an issue where only the tests that were present in `insights/cmd/insights` were being run when building the `ubuntu-insights` Debian package. Instead, now all tests are run in a behavior similar to autopkgtest as expected.
There is additional logic to ensure that the C libs aren't being shipped with the package while still allowing for tests to be run for them.
This PR also cleans up and removes the unnecessary `dh_dwz_override` in the `control` file.
The changelog has been updated with new entries to reflect these changes.
---
[UDENG-7468](https://warthogs.atlassian.net/browse/UDENG-7468)
[UDENG-7468]: https://warthogs.atlassian.net/browse/UDENG-7468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build(insights): Fix build time tests

insights/debian/changelog, insights/internal/constants/constants.go, insights/internal/report/report.go, insights/internal/uploader/export_test.go, insights/internal/uploader/testutils/uploader.go, insights/internal/uploader/upload.go, insights/internal/uploader/uploader.go, insights/internal/uploader/uploader_test.go
Add fixed limits to concurrent report and source processing when uploading.
Presently, the theoretical infinite number of goroutines can be spawned when the client is processing and uploading reports. Where `r` is the number of reports across all targeted sources and `s` is the number of targeted sources, there is a maximum limit of `r+s`  goroutines that may be spawned, with r routines potentially attempting to send out HTTP requests. 
There is a 150 report limit per source on how many reports are allowed to be on the disk. Typically, a collection call will remove old reports if there are too many already on the disk, limiting the impact of the go routine spawns. But it is possible for abuse to result in a considerable number of sources and reports that the uploader will treat as valid. …
=> feat(insights): Add fixed limits to concurrent report and source processing when uploading

insights/debian/changelog
Syncs the changelog for 0.3.0 with the downstream package release.
- Formatting fix
- Reference release launchpad bug
A git tag should be pushed once this PR is merged.
=> maint(insights): Sync changelog 0.3.0 with downstream release

insights/api.go
This PR changes the Go API behavior to utilize the global slogger instead of a new logger defined and configured internally.
This change is intended to improve the experience for use cases where the caller application is using the global default slogger, possibly modifying this logger. By defaulting to this slogger, the caller no longer needs to pass it if they are using it. If they are not using it, the old internal logger matches what the default logger would have been, so there is no behavior change there.
It is important to note that we don't make changes internally to the default slogger other than in parts of the CLI implementation, meaning we don't interfere with the Go API consumer's default slogger.
=> feat(insights): Go API defaults to global slogger if one is not passed

.github/workflows/qa-debian.yaml
This PR implements matrix support for setting the target Ubuntu version as well as setting the autopkgtest host runner.
Note that this PR does not implement support for setting the host runner for trivial tests. Due to how artifact naming is done in the action we use, architecture changes will cause artifact name conflict errors. https://github.com/canonical/desktop-engineering/blob/main/gh-actions/common/build-debian/action.yml 
---
[UDENG-7384](https://warthogs.atlassian.net/browse/UDENG-7384)
[UDENG-7384]: https://warthogs.atlassian.net/browse/UDENG-7384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci(qa-deb): Matrix support for target Ubuntu version and autopkgtest host runner

go.work
Bumps toolchain to 1.24.6 to resolve `GO-2025-3849` which is present in the server module.
=> deps: Bump toolchain to 1.24.6

insights/api.go, insights/internal/collector/collector.go, insights/internal/uploader/upload.go
This PR ensures that certain typed errors are exposed in the Go API. This is to allow for API callers to react to these errors more precisely and easily.
=> feat(insights): Expose typed errors in the Go API

.github/workflows/qa-debian.yaml
This PR modifies the trigger conditions of the qa-deb workflow, including adding a supporting job to get the diff.
The `Check modified files` job was copied from the Authd repository with some changes to support our needs.
This workflow now uses mostly an allow method when triggering on pull request events to be more specific.
- Anything in the `insights/` directory
- This workflow `.github/workflows/qa-debian.yaml`
- Excluding markdown file only changes
Using the new `Check modified files` job, autopkgtests now only run with the following additional triggers:
- Push events to main branch
- When a file in the insights/debian/ directory is modified
- When this file is modified
- When a tag is pushed
- When a release is created
This was done as this job can add a good amount of extra time, …
=> ci(qa-deb): Change trigger conditions

insights/C/libinsights.go, insights/C/libinsightstest.go, insights/C/types.h, insights/debian/changelog, insights/debian/libinsights0.symbols
This PR renames the C bindings functions and types for consistency and to improve idiomatic-ness. It also puts into use the previous unused custom const char type (named `Cchar` before, now `CInsightsChar`) in order for the generated headers to use constant char types where appropriate. 
Since the bindings might be used in a variety of situations, we are just following GNU conventions here https://www.gnu.org/prep/standards/html_node/Names.html.
=> refactor(insights): rename functions and types for consistency in C API

insights/debian/prepare-source.sh
Previously, if `go generate` was ran locally, it wouldn't get cleaned before packaging. Especially since that folder is included in `.gitignore`, it was easy to overlook this and actually create deb package sources that include the `generated` folder. This is especially an issue if the C bindings shared libs were generated.
This PR simply ensures that this folder is removed.
=> fix(insights): Clean up generated sources in prepare-source.sh

insights/C/libinsights.go, insights/C/libinsights_test.go, insights/C/libinsightstest.go, insights/C/testdata/TestCompile/golden/arguments_get_converted, insights/C/testdata/TestCompile/golden/empty_values_are_empty, insights/C/testdata/TestCompile/golden/error_returns_error_string, insights/C/testdata/TestCompile/golden/null_values_are_empty, insights/C/testdata/TestCompile/golden/report_is_not_returned_in_error_case, insights/C/testdata/TestCompile/golden/report_is_not_returned_when_outreport_is_nil, insights/C/testdata/TestCompile/golden/report_is_returned_safely_when_empty, insights/C/testdata/TestCompile/golden/report_is_returned_when_outreport_and_outreportlen_are_provided, insights/C/testdata/TestCompile/golden/report_return_is_safe_when_output_has_null_terminator_in_middle, insights/C/types.h, insights/api.go, insights/api_test.go, insights/debian/changelog
This PR exposes the collector compile method to both the Go API and to the C bindings.
The intent behind this is to provide an easier-to-use method of just getting a compiled report without writing to disk. Though this could have been achieved by passing dryrun and force to the collect methods, this method simplifies this significantly, eliminating most arguments that are only used for writing.
=> feat(insights): Expose collector compile method

insights/internal/collector/collector.go
This PR downgrades the opt-out log at write time from `Warn` to `Info` as this is standard business logic and not indicative of an exception. Additionally, the message itself has been rewritten for consistency and clarity.
=> fix(insights): Update log message for consent opt-out scenario

insights/autostart/systemd/ubuntu-insights-upload.timer
Fixes the upload systemd timer description to reflect the 8-minute post-boot timer, not 5 minutes.
=> fix(insights): Fix upload timer description to reflect 8 minutes after boot

SECURITY.md
An initial security policy with guidelines on reporting vulnerabilities via GitHub.
Closes #212 
---
[UDENG-7298](https://warthogs.atlassian.net/browse/UDENG-7298)
[UDENG-7298]: https://warthogs.atlassian.net/browse/UDENG-7298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Add security policy and vulnerability reporting guidelines

insights/autostart/systemd/ubuntu-insights-collect.service, insights/autostart/systemd/ubuntu-insights-upload.service
In certain environments, collections triggered by systemd fail due to a permissions error when trying to create the `~/.cache/ubuntu-insights folder`. It is likely this happens with other folders as well. This only occurs with systemd-triggered collections and does not occur when running the same command without systemd containment. Additionally, it also appears not to be an issue on Plucky or Questing, though this could be due to the test environment not triggering `ProtectHome`.
```
ERROR failed to collect insights: failed to create cache directory: mkdir ~: permission denied
```
This PR resolves this issue while preserving the same containment score as before. 
---
[UDENG-7697](https://warthogs.atlassian.net/browse/UDENG-7697)
[UDENG-7697]: …
=> fix(insights): Fix systemd permissions error in certain environments

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, CONTRIBUTING.md, insights/README.md
This PR cleans up various repository files and repository-level documentation.
- Bug report template
- Remove references to snaps
- Add additional instructions on getting relevant information, including an optional script for Ubuntu users
- Add references to the security policy
- Feature request template
- Remove references to snaps
- Remove unnecessary sections
- Add references to the security policy
-  `CONTRIBUTING.md`
- Add dependency information
- Add build instruction
- Add information about the test suite
- Add code style information
- Add references to the security policy
- Fix broken Launchpad link
- Add Go reference documentation badge to `insights/` README
- Remove bad entry from CODEOWNERS file
---
[UDENG-7298](https://warthogs.atlassian.net/browse/UDENG-7298)
[UDENG-7298]: …
=> docs: Cleanup repository files and documentation

insights/api.go
This PR prevents the misleading log "No source provided, defaulting to platform" from being printed when using `Compile` via either the Go API or C bindings. Since `source` has no meaning when using `Compile`, this message does not make sense.
This is only a workaround for now until the collector is refactored. Currently, this message is caused by the sanitation of the collector config when a new collector is being made. If the source is not set at sanitation time, then this message is logged. Since `source` is meaningless when only compiling, this workaround just sets it to an arbitrary value.
=> fix(insights): Fix misleading "No source provided" log when using Compile

insights/debian/changelog
Add a changelog entry for insights version 0.6.1
This is a bug-fix release.
---
[UDENG-7713](https://warthogs.atlassian.net/browse/UDENG-7713)
[UDENG-7713]: https://warthogs.atlassian.net/browse/UDENG-7713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> maint(insights): Add changelog entry for version 0.6.1

server/README.md, server/internal/common/constants/constants.go
This PR changes the default reports dir to use the user cache path. This may be a breaking change.
While it is expected that most users will set this manually (like how it is in the charm currently), the previous default value required the services to be run as root or for the default directory to already exist with special permissions set up to allow for the services to read and write to them. Since we don't package and ship the binaries outside a charm, this isn't something that can be automated.
By using `~/.cache/` instead, we get around this and remove the requirement to run the service as root or do extra setup when using the default value.
=> fix(server): Change the default reports dir to use the user cache path

.github/workflows/qa.yaml
We're about to merge a breaking change in the `go/code-sanity` GitHub Action ([use of golangci-lint v2 instead of v1](https://github.com/canonical/desktop-engineering/pull/75)), so to avoid breaking the CI, we need to switch to `go/code-sanity@v1` instead of `go/code-sanity@main`.
Once the change has been merged, I will prepare a follow-up PR to migrate the `.golangci.yaml` to the v2 format and use `go/code-sanity@v2`.
UDENG-7801
=> ci: Use go/code-sanity@v1

insights/debian/changelog, insights/go.mod, insights/go.sum, server/go.mod, server/go.sum
Release 0.6.2 is mostly resolving an issue with a broken patch downstream as well as a few new Go dependency updates. 
This PR includes a bump for the common module version, which itself had dependency updates.
=> maint(insights): New changelog entry for 0.6.2

insights/debian/control
This PR changes the section of the main `ubuntu-insights` package to `utils` from `golang`.
=> fix(insights): Change section of the main package to utils

server/cmd/ingest-service/daemon/daemon.go, server/cmd/ingest-service/daemon/daemon_test.go, server/cmd/ingest-service/daemon/migrate.go, server/internal/ingest/database/database.go, server/internal/ingest/database/database_test.go, server/internal/ingest/database/testdata/TestURI/golden/basic_config, server/internal/ingest/database/testdata/TestURI/golden/handles_custom_scheme, server/internal/ingest/database/testdata/TestURI/golden/handles_no_password, server/internal/ingest/database/testdata/TestURI/golden/handles_no_port, server/internal/ingest/database/testdata/TestURI/golden/handles_no_sslmode
This PR fixes a number of potential leaks of database credentials in logs.
- The parsed config in the logs when starting the ingest service now redacts the password first.
- URI building for both standard operation and for the migrate command has been reworked to improve its reciliency.
-  This change prevents a situation where errors would cause leaks should a password but no user be passed to the service.
=> fix(ingest-service): Fix potential leaking of credentials in logs 

.github/actions/prepare-environment/action.yaml, .github/workflows/lrc-qa.yaml, .github/workflows/qa.yaml
This PR refactors the "QA & sanity checks" workflow and adds TiCS integration.
The integration of TiCS surfaced some challenges with the prior setup for the QA workflow, as it requires you to upload coverage files from a very specific place. In the process of doing this, the workflow has been refactored with a number of additional fixes and changes. Since everything ties in with each other, it is a bit difficult to split up this PR
- Add new scheduled trigger
- 4:15 UTC weekly on Monday to try and avoid heavy hours
- We don't really need a daily since we also trigger on push to main. 
- Create a new `process-coverage` job
- Processes the coverage outputs from the coverage tests, combining and converting them to Cobertura
- Upload all coverage results to Codecov in one go
- Trigger TiCS …
=> ci: Refactor QA & sanity checks workflow and add TiCS integration

.github/workflows/qa.yaml
This PR aims to fix the missing build dependency error present with TiCS analysis runs in QServer mode.
As part of this, the decision of whether to use QServer or Client mode has been abstracted out into a separate step.
=> ci: Fix missing dependency for TiCS QServer mode

.github/workflows/qa.yaml
Updates the QA workflow GH runners from `windows-2022` to `windows-2025`, `macos-13` to `macos-15-intel`, and `macos-14` to `macos-15`. 
The `macos-13` GitHub runner image is now deprecated, so we are required to move to something else. The other changes are just to keep things updated.
=> ci: Update GH runner images
